# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'pucCloud' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pucCloud
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
pod 'Firebase/Functions'

  target 'pucCloud-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pucCloudTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'pucCloud-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for pucCloud-tvOS

end
